package org.ispcluj;

//TODO: REQ-1
public record Train(String id, String type, String origin) {
    // you can create a classic Train class and delete this if it's better for you
    // here you can add extra methods if needed (getters, setters, hashCode, equals are already generated by the record)
    //check if toString works without generating it, if not and you need it, generate it.
    public void validateSignals() throws SignalFailureException{
        if(origin==null || origin.isEmpty()){
            throw new SignalFailureException("Invalid origin");
        }
        //check and throw SignalFailureException if needed from here
    }
}
